name: Checkmarx Sync

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    uses: acacoop/Security-Workflows/workflows/repository-sync.yml@main

    with:
      target_repo: repo-pruebaSec-destino

    secrets:
      SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
