name: Sync Repository to Checkmarx

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    uses: acacoop/Security-Workflows/.github/workflows/repository-sync.yml
    with:
      target_repo: repo-checkmarx-test
    secrets: inherit
